package org.vanhack.sevensnake.model;

import java.io.File;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

import org.assertj.core.api.Assertions;
import org.junit.Test;
import org.vanhack.sevensnake.seeker.Kernel;
import org.vanhack.sevensnake.seeker.SnakeMatchSeeker;

public class SnakeProcessorTest {

	@Test
	public void shouldFindAMatch(){
		Graph graph = new Graph(new File(getClass().getResource("/match.csv").getFile()));
		SnakeMatchSeeker processor = new SnakeMatchSeeker(graph);
		SnakeMatch m = processor.findMatch();
		Assertions.assertThat(m).isNotNull();
		System.out.println(m);
	}
	

	@Test
	public void shouldFindAMatchInChallenge(){
		Graph graph = new Graph(new File(getClass().getResource("/challengeSample.csv").getFile()));
		SnakeMatchSeeker processor = new SnakeMatchSeeker(graph);
		SnakeMatch m = processor.findMatch();
		Assertions.assertThat(m).isNotNull();
		System.out.println(m);
	}
	
	
	private static final List<String> data = Arrays.asList("new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(3,3), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(2,2), new Node(2,0), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(4,1), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,1), new Node(2,2), new Node(1,1), new Node(0,1), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,2), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(5,0), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(4,0), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(4,0), new Node(3,0), new Node(4,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(3,0), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(3,3), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(2,0), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(4,1), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(5,1), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(3,3), new Node(2,3), new Node(1,3), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(5,0), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(4,0), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(4,0), new Node(3,0), new Node(4,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(3,0), new Node(2,0), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(4,1), new Node(2,0), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(5,1), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,2), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(4,0), new Node(3,0), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(5,0), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(3,0), new Node(4,1), new Node(2,0), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(5,1), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(4,0), new Node(3,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(0,5), new Node(0,6))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,2), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(5,1), new Node(3,0), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(4,0), new Node(3,0), new Node(4,1), new Node(2,0), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(5,0), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(1,5), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,2), new Node(4,0), new Node(4,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(4,0), new Node(5,1), new Node(3,0), new Node(4,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(1,4), new Node(0,4), new Node(1,5))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(5,0), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(5,0), new Node(4,0), new Node(5,1), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(0,4), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(1,4), new Node(1,5))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(2,4), new Node(0,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(5,0), new Node(5,1), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(1,1), new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(2,3), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(6,0), new Node(5,0), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(1,4), new Node(1,5))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(0,2), new Node(1,3), new Node(2,4), new Node(0,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(0,4), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(2,3), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(2,2), new Node(0,1), new Node(2,3), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(2,3), new Node(0,2), new Node(1,3), new Node(2,4), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(1,5))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(2,4), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(1,4), new Node(0,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(0,4), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(3,3), new Node(0,1), new Node(2,3), new Node(0,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(1,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(1,5))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(1,3), new Node(2,4), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(1,5), new Node(0,5))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(1,1), new Node(0,0), new Node(0,1), new Node(0,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(0,1), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(3,3), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(2,3), new Node(1,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(2,4), new Node(1,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(0,1), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(2,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,1), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(1,2), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(3,3), new Node(0,1), new Node(1,2), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(2,2), new Node(3,3), new Node(0,1), new Node(1,2), new Node(2,3), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(1,2), new Node(2,3), new Node(1,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(2,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(2,3), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(1,3), new Node(1,4), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(1,3), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(3,0), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(0,1), new Node(2,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(2,2), new Node(1,1), new Node(1,2), new Node(0,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(1,2), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(2,2), new Node(1,2), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(3,3), new Node(1,2), new Node(2,3), new Node(1,3))),",
			"new HashSet<>(Arrays.asList(new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(0,1), new Node(1,2), new Node(2,3))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(0,0), new Node(2,2), new Node(3,3), new Node(0,1), new Node(1,2), new Node(0,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(2,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(2,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,2), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,3), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(1,3), new Node(1,4), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(0,2), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(3,0), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(0,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(2,2), new Node(0,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(2,2), new Node(0,1), new Node(2,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,1), new Node(0,2), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(1,2), new Node(0,2), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(2,3), new Node(1,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(1,2), new Node(2,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(0,1), new Node(2,3))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(0,1), new Node(1,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(2,3), new Node(2,4))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(0,0), new Node(2,2), new Node(0,1), new Node(1,2), new Node(0,2), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,2), new Node(1,3), new Node(0,2), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(1,4), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(1,1), new Node(0,1), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,0), new Node(0,0), new Node(0,1), new Node(3,0), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(0,2), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(0,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(3,0), new Node(3,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,1), new Node(1,2), new Node(0,1), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(1,1), new Node(2,2), new Node(0,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,1), new Node(0,2), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(2,3))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(1,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3), new Node(0,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(2,3), new Node(2,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(1,2), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(1,3), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(1,3), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(2,4), new Node(1,4), new Node(0,4), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(0,1), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(0,1), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(0,1), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(1,2), new Node(0,2), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(1,1), new Node(0,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,1), new Node(1,2), new Node(0,1), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(3,3), new Node(2,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(3,3))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(3,3), new Node(0,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(1,2), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(0,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,1), new Node(0,2), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,3), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(1,3), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,2), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(3,0), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(2,2), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(1,1), new Node(0,1), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(1,1), new Node(0,1), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(2,2), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(1,2), new Node(0,2), new Node(4,0), new Node(3,0), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(1,1), new Node(0,1), new Node(0,2), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(2,2), new Node(3,3), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(3,3), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(2,2), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(0,0), new Node(1,1), new Node(0,1), new Node(3,1), new Node(4,2))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(1,2), new Node(0,2), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,1), new Node(1,2), new Node(0,1), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(2,2), new Node(1,2), new Node(0,2), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(2,2), new Node(2,3), new Node(1,3), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(3,2), new Node(2,2), new Node(1,2), new Node(1,3), new Node(0,3), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(0,0), new Node(0,1), new Node(4,0), new Node(3,0), new Node(4,1), new Node(2,0))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(2,1), new Node(0,0), new Node(1,1), new Node(4,0), new Node(3,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(1,1), new Node(0,1), new Node(3,0), new Node(4,1), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(1,0), new Node(3,2), new Node(0,0), new Node(2,2), new Node(3,0), new Node(2,0), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(0,0), new Node(1,1), new Node(0,1), new Node(4,0), new Node(4,1), new Node(3,1))),",
			"new HashSet<>(Arrays.asList(new Node(2,1), new Node(3,2), new Node(1,1), new Node(0,1), new Node(3,0), new Node(2,0), new Node(3,1)))));");
	
	@Test
	public void aiaiai(){
		for(int i = 0; i < Kernel.KERNEL.size(); i++){
			checkbounds(Kernel.KERNEL.get(i),i);
		}
	}
	
	public void checkbounds(Collection<Node> nodes,int index){
		List<Node> list = nodes.stream().filter(node -> {
			int i = 0;
			if( nodes.contains(node.atTop()) ){
				i++;
			}
			if( nodes.contains(node.atBottom()) ){
				i++;
			}
			if( nodes.contains(node.atLeft()) ){
				i++;
			}
			if( nodes.contains(node.atRight()) ){
				i++;
			}
			if(i > 2){
				return true;
			}
			return false;
		}).collect(Collectors.toList());
		if(!list.isEmpty()){
			System.out.println(data.get(index));
		}
	}
}
